version: '3.7'
services:
  pgc.charge.api:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - DOTNET_SYSTEM_NET_HTTP_USESOCKETSHTTPHANDLER=0
      - DOTNET_SYSTEM_NET_SECURITY_ENABLELEGACYTLS=1
      - DOTNET_SYSTEM_NET_SECURITY_SSLPROTOCOLS=Tls12
    ports:
      - "5000:5000"
      - "8080:8080"
    depends_on:
      - db
    networks:
      - network-officecom
  db:
    image: "mcr.microsoft.com/mssql/server:2022-latest"
    environment:
      SA_PASSWORD: "Master@123"
      ACCEPT_EULA: "Y"
      MSSQL_DATABASE: "pgc"
    ports:
      - "1433:1433"
    networks:
      - network-officecom

networks:
  network-officecom:
    driver: bridge